[workspace]
resolver = "3"
members = ["api", "entities", "migration"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
entities = { path = "entities" }
migration = { path = "migration" } 
