[workspace]
resolver = "3"
members = ["services/api", "libs/entities", "migration", "services/ws", "libs/common"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
entities = { path = "libs/entities" }
