[package]
name = "transfer-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
redis = { version = "0.32.7", features = ["connection-manager", "tokio-comp"] }
entities = { workspace = true }